- name: installing catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: downloading the node source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  
  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check user already exists or not
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true
  
  - name: print the out of user
    ansible.builtin.debug:
      msg: "Output : {{user}}"

  - when: user.rc != 0
    name: create user roboshop
    ansible.builtin.user:
      name: roboshop
  
  - name: check the /app directory already exists or not
    ansible.builtin.stat:
      path: /app
    register: Directory
    ignore_errors: true
  
  - name: print the output of directory
    ansible.builtin.debug:
      msg: "output : {{Directory}}"

  - name: create directory /app
    ansible.builtin.file:
      path: /app
      state: directory
    when: Directory.stat.exists == False
  
  # - name: download the catalogue artifact
  #   ansible.builtin.get_url:
  #     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
  #     dest: /tmp/catalogue.zip
  
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /usr/local/bin
      remote_src: yes
  
  - name: npm installing
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: copy to catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: enable and start and daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start and daemon-reload
    ansible.builtin.systemd_service:
      name: catalogue
      enabled: true
      state: restarted
  
  - name: copy mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: installing mongodb-org-shell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed
      
  - name: load the scema
    ansible.builtin.shell: 'mongo --host mongodb.venkateshamsonnalia143.online < /app/schema/catalogue.js'

      
    
  

    

  