- name: Installing mongoDB component
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
      
  - name: installing mongodb-org
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  
  - name: start and enable mongod services
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started
      
  - name: replace the 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      
  - name: restart mongod services
    ansible.builtin.service:
      name: mongod
      state: restarted